In [1]:
import numpy as np
import pandas as pd
import pandas as pd
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")
# sklearn preprocessing for dealing with categorical variables
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing

from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
from sklearn import metrics
import calendar
import datetime as dt
import datetime
import pickle
import azureml.train.automl
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import median_absolute_error
from math import sqrt
from lifelines.utils import k_fold_cross_validation
from dateutil.relativedelta import relativedelta
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
pd.set_option('display.float_format', lambda x: '%.3f' % x)

import matplotlib.pyplot as plt
from matplotlib.image import imread
import pandas as pd
import seaborn as sns
from sklearn.datasets.samples_generator import (make_blobs,
                                                make_circles,
                                                make_moons)
from sklearn.cluster import KMeans, SpectralClustering
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_samples, silhouette_score

%matplotlib inline
sns.set_context('notebook')
plt.style.use('fivethirtyeight')
from warnings import filterwarnings
filterwarnings('ignore')

Duplicate key in file '/Users/at185217/.matplotlib/matplotlibrc' line #2.

In [2]:
df = pd.read_csv('EDL_Train.csv')
df.columns = df.columns.str.replace(r'train_data_t2p.', '')
df['customer_nbr'] = df['customer_nbr'].astype(str)
df['invoice_nbr'] = df['invoice_nbr'].astype(str)
df["ratio_closed_0"] = df["closed_bucket_0"]/df["count_paid_invoices"]
df["ratio_closed_1"] = df["closed_bucket_1"]/df["count_paid_invoices"]
df["ratio_closed_2"] = df["closed_bucket_2"]/df["count_paid_invoices"]
df["ratio_closed_3"] = df["closed_bucket_3"]/df["count_paid_invoices"]
df["ratio_closed_4"] = df["closed_bucket_4"]/df["count_paid_invoices"]

In [3]:
df.head()

,customer_nbr,country_code,invoice_nbr,invoice_base_amount,commited_days,payment_term,invoice_category,delay_status,dso2,invoice_oks,tm_invoice,om_invoice,hsr_sca_invoice,sca_invoice,saas_oks_invoice,hsr_tm_invoice,hsr_invoice_oks,hsr_om_invoice,other_invoice_type_name,finance,retail,hospitality,t_and_t,tlg,financial_banking_cfi,financial_banking_major,financial_channel,financial_other_financial_serv,hospitality_channel,hospitality_eating_drinking_qs,hospitality_eating_drinking_ts,hospitality_sports_recreation,retail_channel,retail_cstore_and_petroleum,retail_distribution_wholesale,retail_drug,retail_food_and_mass,retail_public_sector,retail_specialty_retail,t_and_t_technology,t_and_t_telecom,tlg_channel,tlg_gaming,tlg_lodging,tlg_travel,other_industry,invoice_date,aging_date,payment_due_date,actual_date_closed,day_of_month_created,month_num_created,day_of_week_created,day_of_month_due,month_num_due,day_of_week_due,day_of_month_age,month_num_age,day_of_week_age,me_due_date,me_inv_date,mme_due_date,mme_inv_date,count_prepaid_invoices,ratio_prepaid_invoices,count_paid_invoices,count_delayed_invoices,ratio_delayed_invoices,paid_invoices_amount_us,delayed_paid_invoices_amount,ratio_late_paid_amount,avg_days_late_paid_invoices_closed,count_outstanding_invoices,count_delayed_outstanding_invoices,ratio_outstanding_invoices,outstanding_invoices_amount,delayed_outstanding_invoices_amount,ratio_late_outstanding_amount,avg_days_late_outstanding_invoices_open,closed_bucket_0,closed_bucket_1,closed_bucket_2,closed_bucket_3,closed_bucket_4,open_60_more,total_invoice_lines,hw,sw,swm,hwm,ps,ts,other_category,paid_status,customer_segment,ratio_closed_0,ratio_closed_1,ratio_closed_2,ratio_closed_3,ratio_closed_4
0,10000209,1,800122721,511.000,3,1,0,0,3,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2019-06-14,2019-06-14,2019-06-17,2019-06-17,14,6,4.000,17,6,0.000,14,6,4.000,0,0,0,1,0,0.000,43,20,0.470,18893.430,8948.630,0.470,1.400,0.000,0,0.000,0.000,0.000,0.000,0.000,23,20,0,0,0,0,4,0.000,0.000,0.000,0.000,0.000,0.000,1.000,1,1,0.535,0.465,0.000,0.000,0.000
1,10000209,1,800135628,365.230,3,1,0,0,3,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2019-11-12,2019-11-12,2019-11-15,2019-11-15,12,11,1.000,15,11,4.000,12,11,1.000,0,0,0,1,0,0.000,43,20,0.470,18893.430,8948.630,0.470,1.400,0.000,0,0.000,0.000,0.000,0.000,0.000,23,20,0,0,0,0,4,0.000,0.000,0.000,0.000,0.000,0.000,1.000,1,1,0.535,0.465,0.000,0.000,0.000
2,10000210,1,6500790618,266.000,30,1,0,4,250,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2018-09-13,2018-09-13,2018-10-13,2019-05-21,13,9,3.000,13,10,5.000,13,9,3.000,0,0,1,1,0,0.000,22,6,0.270,6704.000,1596.500,0.240,59.330,0.000,0,0.000,0.000,0.000,0.000,0.000,16,4,0,0,2,0,20,0.000,0.000,0.000,0.000,0.000,0.000,1.000,1,1,0.727,0.182,0.000,0.000,0.091
3,10000716,1,6501127642,320.000,30,1,0,0,30,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2019-07-10,2019-07-10,2019-08-09,2019-08-09,10,7,2.000,9,8,4.000,10,7,2.000,0,0,1,1,0,0.000,20,8,0.400,17135.000,13465.000,0.790,23.750,0.000,0,0.000,0.000,0.000,0.000,0.000,12,6,1,0,1,0,16,0.000,0.000,0.000,0.000,0.000,0.000,1.000,1,1,0.600,0.300,0.050,0.000,0.050
4,10000719,1,6500928201,136.000,30,1,0,0,30,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2019-01-14,2019-01-14,2019-02-13,2019-02-13,14,1,0.000,13,2,2.000,14,1,0.000,0,0,0,1,2,0.130,16,5,0.310,2562.500,1066.500,0.420,17.200,6.000,6,1.000,817.500,817.500,1.000,97.330,11,4,1,0,0,4,4,0.000,0.000,0.000,0.000,0.000,0.000,1.000,1,1,0.688,0.250,0.062,0.000,0.000

In [4]:
def cc(row):
    if row['country_code']==1:
        return 'US'
    else:
        return 'CA'
    
df['country_code'] =df.apply(lambda row: cc(row), axis=1)

In [5]:
df.country_code.value_counts()

US    3062516
CA     472881
Name: country_code, dtype: int64

In [9]:
def it(row):
    if row['invoice_oks']==1:
        return 'invoice_oks'
    elif row['tm_invoice']==1:
        return 'tm_invoice'
    elif row['om_invoice']==1:
        return 'om_invoice'
    elif row['hsr_sca_invoice']==1:
        return 'hsr_sca_invoice'
    elif row['sca_invoice']==1:
        return 'sca_invoice'
    elif row['saas_oks_invoice']==1:
        return 'saas_oks_invoice'
    elif row['hsr_tm_invoice']==1:
        return 'hsr_tm_invoice'
    elif row['hsr_invoice_oks']==1:
        return 'hsr_invoice_oks'
    elif row['hsr_om_invoice']==1:
        return 'hsr_om_invoice'
    elif row['other_invoice_type_name']==1:
        return 'other_invoice_type'

In [10]:
df['invoice_type'] =df.apply(lambda row: it(row), axis=1)

In [12]:
df.invoice_type.value_counts()

invoice_oks           2377873
tm_invoice             306160
om_invoice             207746
hsr_sca_invoice        199129
sca_invoice            140541
other_invoice_type     101411
hsr_invoice_oks         84470
hsr_om_invoice          59413
hsr_tm_invoice          51691
saas_oks_invoice         6963
Name: invoice_type, dtype: int64

In [18]:
def ind(row):
    if row['financial_banking_cfi']==1:
        return 'financial_banking_cfi'
    elif row['financial_banking_major']==1:
        return 'financial_banking_major'
    elif row['financial_channel']==1:
        return 'financial_channel'
    elif row['financial_other_financial_serv']==1:
        return 'financial_other_financial_serv'
    elif row['hospitality_channel']==1:
        return 'hospitality_channel'
    elif row['hospitality_eating_drinking_qs']==1:
        return 'hospitality_eating_drinking_qs'
    elif row['hospitality_eating_drinking_ts']==1:
        return 'hospitality_eating_drinking_ts'
    elif row['hospitality_sports_recreation']==1:
        return 'hospitality_sports_recreation'
    elif row['retail_channel']==1:
        return 'retail_channel'
    elif row['retail_cstore_and_petroleum']==1:
        return 'retail_cstore_and_petroleum'
    elif row['retail_distribution_wholesale']==1:
        return 'retail_distribution_wholesale'
    elif row['retail_drug']==1:
        return 'retail_drug'
    elif row['retail_food_and_mass']==1:
        return 'retail_food_and_mass'
    elif row['retail_public_sector']==1:
        return 'retail_public_sector'
    elif row['retail_specialty_retail']==1:
        return 'retail_specialty_retail'
    elif row['t_and_t_technology']==1:
        return 't_and_t_technology'
    elif row['t_and_t_telecom']==1:
        return 't_and_t_telecom'
    elif row['tlg_channel']==1:
        return 'tlg_channel'
    elif row['tlg_gaming']==1:
        return 'tlg_gaming'
    elif row['tlg_lodging']==1:
        return 'tlg_lodging'
    elif row['tlg_travel']==1:
        return 'tlg_travel'
    elif row['other_industry']==1:
        return 'other_industry'
    
df['industry'] =df.apply(lambda row: ind(row), axis=1)

In [20]:
df.industry.value_counts()

financial_banking_major           1366418
retail_food_and_mass               370208
hospitality_eating_drinking_qs     358923
financial_channel                  343868
hospitality_eating_drinking_ts     305988
retail_specialty_retail            245369
t_and_t_telecom                    215375
retail_channel                     109937
financial_banking_cfi               73925
t_and_t_technology                  56394
financial_other_financial_serv      24248
hospitality_channel                 19966
retail_cstore_and_petroleum         19874
retail_public_sector                 9536
retail_drug                          5205
hospitality_sports_recreation        4764
retail_distribution_wholesale        2000
tlg_travel                           1930
tlg_channel                          1197
tlg_gaming                            251
tlg_lodging                            21
Name: industry, dtype: int64

In [19]:
df.head()

,customer_nbr,country_code,invoice_nbr,invoice_base_amount,commited_days,payment_term,invoice_category,delay_status,dso2,invoice_oks,tm_invoice,om_invoice,hsr_sca_invoice,sca_invoice,saas_oks_invoice,hsr_tm_invoice,hsr_invoice_oks,hsr_om_invoice,other_invoice_type_name,finance,retail,hospitality,t_and_t,tlg,financial_banking_cfi,financial_banking_major,financial_channel,financial_other_financial_serv,hospitality_channel,hospitality_eating_drinking_qs,hospitality_eating_drinking_ts,hospitality_sports_recreation,retail_channel,retail_cstore_and_petroleum,retail_distribution_wholesale,retail_drug,retail_food_and_mass,retail_public_sector,retail_specialty_retail,t_and_t_technology,t_and_t_telecom,tlg_channel,tlg_gaming,tlg_lodging,tlg_travel,other_industry,invoice_date,aging_date,payment_due_date,actual_date_closed,day_of_month_created,month_num_created,day_of_week_created,day_of_month_due,month_num_due,day_of_week_due,day_of_month_age,month_num_age,day_of_week_age,me_due_date,me_inv_date,mme_due_date,mme_inv_date,count_prepaid_invoices,ratio_prepaid_invoices,count_paid_invoices,count_delayed_invoices,ratio_delayed_invoices,paid_invoices_amount_us,delayed_paid_invoices_amount,ratio_late_paid_amount,avg_days_late_paid_invoices_closed,count_outstanding_invoices,count_delayed_outstanding_invoices,ratio_outstanding_invoices,outstanding_invoices_amount,delayed_outstanding_invoices_amount,ratio_late_outstanding_amount,avg_days_late_outstanding_invoices_open,closed_bucket_0,closed_bucket_1,closed_bucket_2,closed_bucket_3,closed_bucket_4,open_60_more,total_invoice_lines,hw,sw,swm,hwm,ps,ts,other_category,paid_status,customer_segment,ratio_closed_0,ratio_closed_1,ratio_closed_2,ratio_closed_3,ratio_closed_4,invoice_type,industry
0,10000209,US,800122721,511.000,3,1,0,0,3,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2019-06-14,2019-06-14,2019-06-17,2019-06-17,14,6,4.000,17,6,0.000,14,6,4.000,0,0,0,1,0,0.000,43,20,0.470,18893.430,8948.630,0.470,1.400,0.000,0,0.000,0.000,0.000,0.000,0.000,23,20,0,0,0,0,4,0.000,0.000,0.000,0.000,0.000,0.000,1.000,1,1,0.535,0.465,0.000,0.000,0.000,other_invoice_type,hospitality_eating_drinking_ts
1,10000209,US,800135628,365.230,3,1,0,0,3,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2019-11-12,2019-11-12,2019-11-15,2019-11-15,12,11,1.000,15,11,4.000,12,11,1.000,0,0,0,1,0,0.000,43,20,0.470,18893.430,8948.630,0.470,1.400,0.000,0,0.000,0.000,0.000,0.000,0.000,23,20,0,0,0,0,4,0.000,0.000,0.000,0.000,0.000,0.000,1.000,1,1,0.535,0.465,0.000,0.000,0.000,other_invoice_type,hospitality_eating_drinking_ts
2,10000210,US,6500790618,266.000,30,1,0,4,250,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2018-09-13,2018-09-13,2018-10-13,2019-05-21,13,9,3.000,13,10,5.000,13,9,3.000,0,0,1,1,0,0.000,22,6,0.270,6704.000,1596.500,0.240,59.330,0.000,0,0.000,0.000,0.000,0.000,0.000,16,4,0,0,2,0,20,0.000,0.000,0.000,0.000,0.000,0.000,1.000,1,1,0.727,0.182,0.000,0.000,0.091,hsr_sca_invoice,hospitality_eating_drinking_ts
3,10000716,US,6501127642,320.000,30,1,0,0,30,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2019-07-10,2019-07-10,2019-08-09,2019-08-09,10,7,2.000,9,8,4.000,10,7,2.000,0,0,1,1,0,0.000,20,8,0.400,17135.000,13465.000,0.790,23.750,0.000,0,0.000,0.000,0.000,0.000,0.000,12,6,1,0,1,0,16,0.000,0.000,0.000,0.000,0.000,0.000,1.000,1,1,0.600,0.300,0.050,0.000,0.050,hsr_sca_invoice,hospitality_eating_drinking_ts
4,10000719,US,6500928201,136.000,30,1,0,0,30,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2019-01-14,2019-01-14,2019-02-13,2019-02-13,14,1,0.000,13,2,2.000,14,1,0.000,0,0,0,1,2,0.130,16,5,0.310,2562.500,1066.500,0.420,17.200,6.000,6,1.000,817.500,817.500,1.000,97.330,11,4,1,0,0,4,4,0.000,0.000,0.000,0.000,0.000,0.000,1.000,1,1,0.688,0.250,0.062,0.000,0.000,hsr_sca_invoice,hospitality_eating_drinking_ts

In [28]:
def cs(row):
    if row['customer_segment']==1:
        return 'Less Value Customer'
    else:
        return 'High Value Customer'
    
df['customer_segment'] =df.apply(lambda row: cs(row), axis=1)

In [29]:
df.customer_segment.value_counts()

High Value Customer    2727188
Less Value Customer     808209
Name: customer_segment, dtype: int64

##### Closed Invoices

In [30]:
Closed_Invoices = df.loc[df['paid_status'] == 1]

In [32]:
list(df.columns)

['customer_nbr',
 'country_code',
 'invoice_nbr',
 'invoice_base_amount',
 'commited_days',
 'payment_term',
 'invoice_category',
 'delay_status',
 'dso2',
 'invoice_oks',
 'tm_invoice',
 'om_invoice',
 'hsr_sca_invoice',
 'sca_invoice',
 'saas_oks_invoice',
 'hsr_tm_invoice',
 'hsr_invoice_oks',
 'hsr_om_invoice',
 'other_invoice_type_name',
 'finance',
 'retail',
 'hospitality',
 't_and_t',
 'tlg',
 'financial_banking_cfi',
 'financial_banking_major',
 'financial_channel',
 'financial_other_financial_serv',
 'hospitality_channel',
 'hospitality_eating_drinking_qs',
 'hospitality_eating_drinking_ts',
 'hospitality_sports_recreation',
 'retail_channel',
 'retail_cstore_and_petroleum',
 'retail_distribution_wholesale',
 'retail_drug',
 'retail_food_and_mass',
 'retail_public_sector',
 'retail_specialty_retail',
 't_and_t_technology',
 't_and_t_telecom',
 'tlg_channel',
 'tlg_gaming',
 'tlg_lodging',
 'tlg_travel',
 'other_industry',
 'invoice_date',
 'aging_date',
 'payment_due_date',
 'actual_date_closed',
 'day_of_month_created',
 'month_num_created',
 'day_of_week_created',
 'day_of_month_due',
 'month_num_due',
 'day_of_week_due',
 'day_of_month_age',
 'month_num_age',
 'day_of_week_age',
 'me_due_date',
 'me_inv_date',
 'mme_due_date',
 'mme_inv_date',
 'count_prepaid_invoices',
 'ratio_prepaid_invoices',
 'count_paid_invoices',
 'count_delayed_invoices',
 'ratio_delayed_invoices',
 'paid_invoices_amount_us',
 'delayed_paid_invoices_amount',
 'ratio_late_paid_amount',
 'avg_days_late_paid_invoices_closed',
 'count_outstanding_invoices',
 'count_delayed_outstanding_invoices',
 'ratio_outstanding_invoices',
 'outstanding_invoices_amount',
 'delayed_outstanding_invoices_amount',
 'ratio_late_outstanding_amount',
 'avg_days_late_outstanding_invoices_open',
 'closed_bucket_0',
 'closed_bucket_1',
 'closed_bucket_2',
 'closed_bucket_3',
 'closed_bucket_4',
 'open_60_more',
 'total_invoice_lines',
 'hw',
 'sw',
 'swm',
 'hwm',
 'ps',
 'ts',
 'other_category',
 'paid_status',
 'customer_segment',
 'ratio_closed_0',
 'ratio_closed_1',
 'ratio_closed_2',
 'ratio_closed_3',
 'ratio_closed_4',
 'invoice_type',
 'industry']

In [40]:
CI = Closed_Invoices[['customer_nbr','country_code','invoice_nbr','invoice_base_amount','commited_days',
                     'invoice_category', 'invoice_type','industry',
                      'invoice_date', 'aging_date', 'payment_due_date','actual_date_closed',
                     'customer_segment',
                      'count_prepaid_invoices','ratio_prepaid_invoices',
                      'count_paid_invoices','count_delayed_invoices','ratio_delayed_invoices',
                      'paid_invoices_amount_us','delayed_paid_invoices_amount','ratio_late_paid_amount',
                      'avg_days_late_paid_invoices_closed',
                     'total_invoice_lines','hw','sw','swm','hwm','ps','ts','other_category',
                      'closed_bucket_0','closed_bucket_1','closed_bucket_2','closed_bucket_3','closed_bucket_4',
                     'ratio_closed_0','ratio_closed_1','ratio_closed_2','ratio_closed_3','ratio_closed_4']]

In [41]:
CI.head()

  customer_nbr country_code invoice_nbr  invoice_base_amount  commited_days  invoice_category        invoice_type                        industry invoice_date  aging_date payment_due_date actual_date_closed     customer_segment  count_prepaid_invoices  ratio_prepaid_invoices  count_paid_invoices  count_delayed_invoices  ratio_delayed_invoices  paid_invoices_amount_us  delayed_paid_invoices_amount  ratio_late_paid_amount  avg_days_late_paid_invoices_closed  total_invoice_lines    hw    sw   swm   hwm    ps    ts  other_category  closed_bucket_0  closed_bucket_1  closed_bucket_2  closed_bucket_3  closed_bucket_4  ratio_closed_0  ratio_closed_1  ratio_closed_2  ratio_closed_3  ratio_closed_4
0     10000209           US   800122721              511.000              3                 0  other_invoice_type  hospitality_eating_drinking_ts   2019-06-14  2019-06-14       2019-06-17         2019-06-17  Less Value Customer                       0                   0.000                   43                      20                   0.470                18893.430                      8948.630                   0.470                               1.400                    4 0.000 0.000 0.000 0.000 0.000 0.000           1.000               23               20                0                0                0           0.535           0.465           0.000           0.000           0.000
1     10000209           US   800135628              365.230              3                 0  other_invoice_type  hospitality_eating_drinking_ts   2019-11-12  2019-11-12       2019-11-15         2019-11-15  Less Value Customer                       0                   0.000                   43                      20                   0.470                18893.430                      8948.630                   0.470                               1.400                    4 0.000 0.000 0.000 0.000 0.000 0.000           1.000               23               20                0                0                0           0.535           0.465           0.000           0.000           0.000
2     10000210           US  6500790618              266.000             30                 0     hsr_sca_invoice  hospitality_eating_drinking_ts   2018-09-13  2018-09-13       2018-10-13         2019-05-21  Less Value Customer                       0                   0.000                   22                       6                   0.270                 6704.000                      1596.500                   0.240                              59.330                   20 0.000 0.000 0.000 0.000 0.000 0.000           1.000               16                4                0                0                2           0.727           0.182           0.000           0.000           0.091
3     10000716           US  6501127642              320.000             30                 0     hsr_sca_invoice  hospitality_eating_drinking_ts   2019-07-10  2019-07-10       2019-08-09         2019-08-09  Less Value Customer                       0                   0.000                   20                       8                   0.400                17135.000                     13465.000                   0.790                              23.750                   16 0.000 0.000 0.000 0.000 0.000 0.000           1.000               12                6                1                0                1           0.600           0.300           0.050           0.000           0.050
4     10000719           US  6500928201              136.000             30                 0     hsr_sca_invoice  hospitality_eating_drinking_ts   2019-01-14  2019-01-14       2019-02-13         2019-02-13  Less Value Customer                       2                   0.130                   16                       5                   0.310                 2562.500                      1066.500                   0.420                              17.200                    4 0.000 0.000 0.000 0.000 0.000 0.000           1.000               11                4                1                0                0           0.688           0.250           0.062           0.000           0.000

In [42]:
CI['invoice_date'] = pd.to_datetime(CI['invoice_date'])
CI['payment_due_date'] = pd.to_datetime(CI['payment_due_date'])
CI['actual_date_closed'] = pd.to_datetime(CI['actual_date_closed'])

###### Open Invoices

In [47]:
Open_Invoices = df.loc[df['paid_status'] == 0]

In [48]:
OI = Open_Invoices[['customer_nbr','country_code','invoice_nbr','invoice_base_amount','commited_days',
                     'invoice_category', 'invoice_type','industry',
                      'invoice_date', 'aging_date', 'payment_due_date','actual_date_closed',
                     'customer_segment',
                      'count_prepaid_invoices','ratio_prepaid_invoices',
                      'count_paid_invoices','count_delayed_invoices','ratio_delayed_invoices',
                      'paid_invoices_amount_us','delayed_paid_invoices_amount','ratio_late_paid_amount',
                      'avg_days_late_paid_invoices_closed',
                     'total_invoice_lines','hw','sw','swm','hwm','ps','ts','other_category',
                      'closed_bucket_0','closed_bucket_1','closed_bucket_2','closed_bucket_3','closed_bucket_4',
                     'ratio_closed_0','ratio_closed_1','ratio_closed_2','ratio_closed_3','ratio_closed_4']]

In [52]:
OI['invoice_date'] = pd.to_datetime(OI['invoice_date'])
OI['payment_due_date'] = pd.to_datetime(OI['payment_due_date'])

In [54]:
OI.payment_due_date.describe()

count                  651892
unique                    835
top       2019-11-09 00:00:00
freq                    38768
first     2018-01-04 00:00:00
last      2021-12-09 00:00:00
Name: payment_due_date, dtype: object

###### Extracting both to a csv

In [57]:
CI.to_csv('DataRobot_Closed_Invoices.csv', index=False)
OI.to_csv('DataRobot_Jan_Closed_&_Open_Invoices.csv', index=False)

In [58]:
CI.head(50)

   customer_nbr country_code invoice_nbr  invoice_base_amount  commited_days  invoice_category        invoice_type                        industry invoice_date  aging_date payment_due_date actual_date_closed     customer_segment  count_prepaid_invoices  ratio_prepaid_invoices  count_paid_invoices  count_delayed_invoices  ratio_delayed_invoices  paid_invoices_amount_us  delayed_paid_invoices_amount  ratio_late_paid_amount  avg_days_late_paid_invoices_closed  total_invoice_lines    hw    sw   swm   hwm    ps    ts  other_category  closed_bucket_0  closed_bucket_1  closed_bucket_2  closed_bucket_3  closed_bucket_4  ratio_closed_0  ratio_closed_1  ratio_closed_2  ratio_closed_3  ratio_closed_4
0      10000209           US   800122721              511.000              3                 0  other_invoice_type  hospitality_eating_drinking_ts   2019-06-14  2019-06-14       2019-06-17         2019-06-17  Less Value Customer                       0                   0.000                   43                      20                   0.470                18893.430                      8948.630                   0.470                               1.400                    4 0.000 0.000 0.000 0.000 0.000 0.000           1.000               23               20                0                0                0           0.535           0.465           0.000           0.000           0.000
1      10000209           US   800135628              365.230              3                 0  other_invoice_type  hospitality_eating_drinking_ts   2019-11-12  2019-11-12       2019-11-15         2019-11-15  Less Value Customer                       0                   0.000                   43                      20                   0.470                18893.430                      8948.630                   0.470                               1.400                    4 0.000 0.000 0.000 0.000 0.000 0.000           1.000               23               20                0                0                0           0.535           0.465           0.000           0.000           0.000
2      10000210           US  6500790618              266.000             30                 0     hsr_sca_invoice  hospitality_eating_drinking_ts   2018-09-13  2018-09-13       2018-10-13         2019-05-21  Less Value Customer                       0                   0.000                   22                       6                   0.270                 6704.000                      1596.500                   0.240                              59.330                   20 0.000 0.000 0.000 0.000 0.000 0.000           1.000               16                4                0                0                2           0.727           0.182           0.000           0.000           0.091
3      10000716           US  6501127642              320.000             30                 0     hsr_sca_invoice  hospitality_eating_drinking_ts   2019-07-10  2019-07-10       2019-08-09         2019-08-09  Less Value Customer                       0                   0.000                   20                       8                   0.400                17135.000                     13465.000                   0.790                              23.750                   16 0.000 0.000 0.000 0.000 0.000 0.000           1.000               12                6                1                0                1           0.600           0.300           0.050           0.000           0.050
4      10000719           US  6500928201              136.000             30                 0     hsr_sca_invoice  hospitality_eating_drinking_ts   2019-01-14  2019-01-14       2019-02-13         2019-02-13  Less Value Customer                       2                   0.130                   16                       5                   0.310                 2562.500                      1066.500                   0.420                              17.200                    4 0.000 0.000 0.000 0.000 0.000 0.000           1.000               11                4                1                0                0           0.688           0.250           0.062           0.000           0.000
5      10000976           US   200469854               99.690             30                 0  other_invoice_type  hospitality_eating_drinking_ts   2019-09-28  2019-09-28       2019-10-28         2019-10-30  Less Value Customer                      11                   0.520                   21                       9                   0.430                 9364.210                      4920.050                   0.530                             106.890                   40 0.000 0.000 0.000 0.250 0.000 0.000           0.750               12                7                0                0                2           0.571           0.333           0.000           0.000           0.095
6      10000976           US  6006954392             2786.100             30                 0          om_invoice  hospitality_eating_drinking_ts   2019-08-07  2019-08-07       2019-09-06         2019-09-04  Less Value Customer                      11                   0.520                   21                       9                   0.430                 9364.210                      4920.050                   0.530                             106.890                   36 0.170 0.000 0.000 0.000 0.000 0.080           0.750               12                7                0                0                2           0.571           0.333           0.000           0.000           0.095
7      10001030           US  6500922608              268.000             30                 0     hsr_sca_invoice  hospitality_eating_drinking_ts   2019-01-14  2019-01-14       2019-02-13         2019-02-13  Less Value Customer                       0                   0.000                   20                       6                   0.300                 7637.600                      3567.600                   0.470                              20.830                   28 0.000 0.000 0.000 0.000 0.000 0.000           1.000               14                4                1                1                0           0.700           0.200           0.050           0.050           0.000
8      10001180           US  6500960695              586.000             30                 0     hsr_sca_invoice  hospitality_eating_drinking_ts   2019-02-11  2019-02-11       2019-03-13         2019-03-13  Less Value Customer                       0                   0.000                   22                       6                   0.270                13127.040                      3036.080                   0.230                               1.500                   32 0.000 0.000 0.000 0.000 0.000 0.000           1.000               16                6                0                0                0           0.727           0.273           0.000           0.000           0.000
9      10001180           US  6501157447              440.540             30                 0     hsr_sca_invoice  hospitality_eating_drinking_ts   2019-08-11  2019-08-11       2019-09-10         2019-09-10  Less Value Customer                       0                   0.000                   22                       6                   0.270                13127.040                      3036.080                   0.230                               1.500                   24 0.000 0.000 0.000 0.000 0.000 0.000           1.000               16                6                0                0                0           0.727           0.273           0.000           0.000           0.000
10     10001181           US  6501056695               50.000             30                 0     hsr_sca_invoice  hospitality_eating_drinking_ts   2019-05-10  2019-05-10       2019-06-09         2019-06-10  Less Value Customer                       0                   0.000                   22                       5                   0.230                 1350.000                       250.000                   0.190                               1.600                    4 0.000 0.000 0.000 0.000 0.000 0.000           1.000               17                5                0                0                0           0.773           0.227           0.000           0.000           0.000
11     10001736           US   200365386               99.000             30                 0  other_invoice_type  hospitality_eating_drinking_ts   2019-05-25  2019-05-25       2019-06-24         2019-06-24  Less Value Customer                       2                   0.120                   17                       9                   0.530                 8028.390                      5866.690                   0.730                              25.110                   36 0.000 0.000 0.000 0.250 0.000 0.000           0.750                8                3                6                0                0           0.471           0.176           0.353           0.000           0.000
12     10001737           US  6501046945              160.000             30                 0     hsr_sca_invoice  hospitality_eating_drinking_ts   2019-05-10  2019-05-10       2019-06-09         2019-06-10  Less Value Customer                       0                   0.000                   23                       8                   0.350                 3330.000                      1030.000                   0.310                               4.500                    8 0.000 0.000 0.000 0.000 0.000 0.000           1.000               15                8                0                0                0           0.652           0.348           0.000           0.000           0.000
13     10001738           US  6501056582               50.000             30                 0     hsr_sca_invoice  hospitality_eating_drinking_ts   2019-05-10  2019-05-10       2019-06-09         2019-06-10  Less Value Customer                       0                   0.000                   22                       5                   0.230                 4154.000                       666.000                   0.160                               1.600                    4 0.000 0.000 0.000 0.000 0.000 0.000           1.000               17                5                0                0                0           0.773           0.227           0.000           0.000           0.000
14     10001739           US  6501226858              293.150             30                 0     hsr_sca_invoice  hospitality_eating_drinking_ts   2019-10-10  2019-10-10       2019-11-09         2019-11-11  Less Value Customer                       0                   0.000                   23                       6                   0.260                 9454.450                      3036.750                   0.320                               1.500                   16 0.000 0.000 0.000 0.000 0.000 0.000           1.000               17                6                0                0                0           0.739           0.261           0.000           0.000           0.000
15     10001748           US  6007003282              237.380             30                 0          om_invoice  hospitality_eating_drinking_ts   2019-10-30  2019-10-30       2019-11-29         2019-12-24  Less Value Customer                       8                   0.800                   10                       2                   0.200                 1747.000                       242.640                   0.140                             259.500                   12 0.250 0.000 0.000 0.000 0.000 0.000           0.750                8                1                0                0                1           0.800           0.100           0.000           0.000           0.100
16     10001771           US  6501063928               86.000             30                 0     hsr_sca_invoice  hospitality_eating_drinking_ts   2019-05-10  2019-05-10       2019-06-09         2019-06-10  Less Value Customer                       0                   0.000                   16                       3                   0.190                 1824.800                       258.000                   0.140                               1.330                    8 0.000 0.000 0.000 0.000 0.000 0.000           1.000               13                3                0                0                0           0.812           0.188           0.000           0.000           0.000
17     10002130           US  6501265424              325.890             30                 0     hsr_sca_invoice  hospitality_eating_drinking_ts   2019-11-12  2019-11-12       2019-12-12         2019-12-12  Less Value Customer                       0                   0.000                   22                       5                   0.230                 8071.120                      1629.780                   0.200                               1.600                   20 0.000 0.000 0.000 0.000 0.000 0.000           1.000               17                5                0                0                0           0.773           0.227           0.000           0.000           0.000
18     10002421           US  1102462517              706.000             30                 0          tm_invoice            retail_public_sector   2019-09-26  2019-09-26       2019-10-26         2019-11-04  Less Value Customer                       3                   0.040                   77                      74                   0.960               311173.450                    309729.450                   1.000                             206.700                    8 0.000 0.000 0.000 0.250 0.000 0.000           0.750                3               20                0                1               53           0.039           0.260           0.000           0.013           0.688
19     10002421           US  2826157986               93.300             30                 0         invoice_oks            retail_public_sector   2018-03-30  2018-03-30       2018-04-29         2019-11-15  Less Value Customer                       3                   0.040                   77                      74                   0.960               311173.450                    309729.450                   1.000                             206.700                    4 0.000 0.000 0.000 0.000 0.000 0.000           1.000                3               20                0                1               53           0.039           0.260           0.000           0.013           0.688
20     10002421           US  2826889640             3262.430             30                 0         invoice_oks            retail_public_sector   2018-08-17  2018-08-17       2018-09-16         2019-10-07  Less Value Customer                       3                   0.040                   77                      74                   0.960               311173.450                    309729.450                   1.000                             206.700                    8 0.000 0.000 0.000 0.250 0.000 0.000           0.750                3               20                0                1               53           0.039           0.260           0.000           0.013           0.688
21     10002421           US  2827731287             6469.940             45                 0         invoice_oks            retail_public_sector   2019-02-15  2019-02-15       2019-04-01         2019-10-07  Less Value Customer                       3                   0.040                   77                      74                   0.960               311173.450                    309729.450                   1.000                             206.700                    8 0.000 0.000 0.000 0.250 0.000 0.000           0.750                3               20                0                1               53           0.039           0.260           0.000           0.013           0.688
22     10002421           US  2828080584             2097.560             30                 0         invoice_oks            retail_public_sector   2019-04-20  2019-04-20       2019-05-20         2019-10-07  Less Value Customer                       3                   0.040                   77                      74                   0.960               311173.450                    309729.450                   1.000                             206.700                    8 0.000 0.000 0.000 0.250 0.000 0.000           0.750                3               20                0                1               53           0.039           0.260           0.000           0.013           0.688
23     10002421           US  2828697395             2875.150             30                 0         invoice_oks            retail_public_sector   2019-08-29  2019-08-29       2019-09-28         2019-10-07  Less Value Customer                       3                   0.040                   77                      74                   0.960               311173.450                    309729.450                   1.000                             206.700                    8 0.000 0.000 0.000 0.250 0.000 0.000           0.750                3               20                0                1               53           0.039           0.260           0.000           0.013           0.688
24     10002471           US  6500990974            81000.000             30                 1     hsr_sca_invoice  hospitality_eating_drinking_ts   2019-03-12  2019-03-12       2019-04-11         2019-05-28  High Value Customer                       1                   0.100                   10                       9                   0.900              1599000.000                   1518000.000                   0.950                             132.220                    4 0.000 0.000 0.000 0.000 0.000 0.000           1.000                1                1                1                1                6           0.100           0.100           0.100           0.100           0.600
25     10002890           US   300199659              108.510             30                 0      hsr_tm_invoice  hospitality_eating_drinking_ts   2018-12-01  2018-12-01       2018-12-31         2019-10-25  Less Value Customer                       1                   0.040                   26                      20                   0.770                17509.310                     16136.970                   0.920                              73.550                    4 0.000 0.000 0.000 0.250 0.000 0.000           0.750                6                9                0                8                3           0.231           0.346           0.000           0.308           0.115
26     10002891           US  6500959972              175.000             30                 0     hsr_sca_invoice  hospitality_eating_drinking_ts   2019-02-11  2019-02-11       2019-03-13         2019-03-13  Less Value Customer                       0                   0.000                   23                       6                   0.260                 4525.000                      1550.000                   0.340                               1.500                    8 0.000 0.000 0.000 0.000 0.000 0.000           1.000               17                6                0                0                0           0.739           0.261           0.000           0.000           0.000